### ISSUE TITLE
Make static switch per-component

### ISSUE THREAD

**Issue by singhd789** [NOAA-GFDL/fre-cli#208]
**Is your feature request related to a problem? Please describe.**
Currently `do_statics` is a per-experiment switch in the yaml framework in the `[shared][postprocess]` section . User's would like this to be per-component as some components have static components. 

**Describe the solution you'd like**
An option can be to include `staticSources`:
```
 components:
    - type: "atmos"
      sources: "atmos_month"
      sourceGrid: "cubedsphere"
      staticSources: [“atmos_static”, “atmos_month”]
      xyInterp: *PP_XYINTERP96
      interpMethod: "conserve_order2"
      inputRealm: 'atmos'
      timeAverage: True
```
Where if these are defined, `do_statics=True`. Ensure proper handling of this change in workflow.
