### ISSUE TITLE
Make `timeaverage` switch per-component 

### ISSUE THREAD

**Issue by singhd789** [NOAA-GFDL/fre-cli#209]
**Is your feature request related to a problem? Please describe.**
Currently do_timeavgs is a per-experiment switch in the yaml framework in the `[shared][postprocess][switches]` section . User's would like this to be per-component as some components involve time averaging and some do not. 

**Describe the solution you'd like**
An option would be to include the switch with the specific component information
```
 components:
    - type: "atmos"
      sources: "atmos_month"
      sourceGrid: "cubedsphere"
      xyInterp: *PP_XYINTERP96
      interpMethod: "conserve_order2"
      inputRealm: 'atmos'
      timeAverage: True
```
Ensure proper handling of this change in workflow.
