### ISSUE TITLE
Flexible configuration for climatology interval periods

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/fre-cli#350]
**Is your feature request related to a problem? Please describe.**
Fine-grained/flexible configuration for climatology interval periods. Bronx frepp allowed arbitrary timeAverage intervals, which are popular.

To facilitate user buy-in, it would greatly help to similarly support multiple climatology intervals.

Presently, one can set

```
postprocess:
 settings:
    pp_chunk_a: P5Y
    pp_chunk_a: P20Y
switches:
    do_timeavgs: True
```

and have monthly and annual climatologies for the 5 and 20 year intervals.

This has been slightly panned by early users (e.g. Utheri).

**Describe the solution you'd like**

```
  components:
    - type: "atmos_cmip"
      sources: "atmos_month_cmip atmos_8xdaily_cmip atmos_daily_cmip"
      sourceGrid: "cubedsphere"
      xyInterp: *PP_XYINTERP96
      interpMethod: "conserve_order2"
      inputRealm: 'atmos'
      climatologies: [P5Y, P20Y, P100Y]
```

**Describe alternatives you've considered**
Possibly, analysis scripts could do their own timeaveraging, but at times this is quite costly.

**Additional context**
