### ISSUE TITLE
Analysis yaml/Yaml anchor information in experiment specific settings yaml

### ISSUE THREAD

**Issue by singhd789** [NOAA-GFDL/fre-cli#515]
**Describe the bug**
`PP_START` and `PP_STOP` are yaml anchors used in the analysis yamls. However, they are experiment specific, so they will need to be changed with each pp experiment. Currently, if they are defined in the settings.yaml, the anchors are not recognized for some reason. They are recognized in the model yaml however, but this present the issue that these values will have to be edited for each pp/analysis run (depending on the experiment) 

**To Reproduce**
One can use the am5 yaml_workflow config files with analysis scripts and analysis turned on. The `PP_START` and `PP_STOP` references won't be recognized. 

**Expected behavior**
We want experiment specific settings to be able to be defined in an experiment specific settings yaml (if needed). 

**Additional context**
- the configure_yaml_script will need to be changed a bit to account for the [settings].yaml and to keep the yaml anchors available to use
- Model yaml could now include `settings` yaml reference instead of specifying it under `pp` or `analysis`
```
- name:
  settings: /path/to/setting/yaml (any experiment specific settings needed)
  pp:
    - /path/to/pp/yamls
  analysis: 
    - /path/to/analysis/yamls
```
