### ISSUE TITLE
fre pp configure needs update to use reworked pp.yaml

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/fre-cli#9]
Currently, `fre pp configure -y pp.yaml` accepts a yaml file and writes 3 files in the current directory:
- rose-suite.conf
- app/regrid-xy/rose-app.conf
- app/remap-pp-components/rose-app.conf

The current pp.yaml looks like this (https://github.com/NOAA-GFDL/fre-cli/blob/main/fre/frepp/edits-template.yaml) and has an associated schema (https://github.com/NOAA-GFDL/fre-cli/blob/main/fre/frepp/schema.json).

Chris has reworked that pp.yaml structure to be more Bronx XML-like. Still up for debate / tweaks, though.

```
refineDiags:
  - script: "/path/to/abs_path/script"
  - script: "path/to/script/in/repo"

preAnalysis:
  - script: "/path/to/preanalysis/script"

settings:
  history_segment:
  start: 1980
  stop:
  site: "ppan"
  fre_analyis_home:
  pp_chunk_a:
  pp_chunk_b:
  grid_spec: "/path/to/tarfile"

switches:
  clean_work: true
  do_mdtf: false
  do_statics: true
  do_timeavgs: true
  do_refinediag: false
  do_atmos_plevel_masking: true
  do_preanalysis: false

directories:
  history: 
  pp:
  ptmp:
  history_refined:
  analysis:

metadata:
  experiment:
  platform:
  target:

components:
  - type: "atmos_cmip"
    source: atmos_month_cmip
    sourceGrid: atmos-cubedsphere
    xyInterp: 288,180
    interpMethod: conserve_order2
    timeSeries:
      - freq: 3hr
        source: atmos_8xdaily_cmip
        chunkLength: 1yr
      - freq: daily
        source: atmos_daily_cmip
        chunkLength: 1yr
        variables: huss tasmin tasmax tas pr psl sfcWind hurs uas vas zg500 ua10 ua850 va850 ua200
  - type: aerosol_cmip
    xyInterp: 288,180
    source: aerosol_month_cmip
    sourceGrid: atmos-cubedsphere
    interpMethod: conserve_order1
    timeSeries:
      - freq: "monthly"
        chunkLength: 1yr
      - freq: monthly
        chunkLength: 1yr
        source: atmos_month_refined
```

So we'd like `fre pp configure` to use this reworked pp.yaml instead.
