### ISSUE TITLE
Expand experiment, platform, target in pp.yaml definitions

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/fre-cli#99]
Currently, we specify directories simply, e.g.

```
  directories:
    history_dir: "/archive/c2b/am5/2022.01/c96L65_am5f1a0r0_amip/gfdl.ncrc5-intel22-classic-prod-openmp/history"
    pp_dir: "/archive/$USER/canopy/am5/c96L65_amip/gfdl.ncrc5-deploy-prod-openmp/pp"
    ptmp_dir: "/xtmp/$USER/ptmp"
    analysis_dir: "/nbhome/$USER/canopy/analysis/am5_c96L65_amip"
```

Bronx FRE directories allow specification in terms of the experiment, platform, target, stem, and others: see

https://sites.google.com/noaa.gov/oar-gfdl-msd-docs/fre-documentation/fre-documentation/xml-files?authuser=0#h.mmnsmti49ogn

e.g. the above directories could be specified more generically:

```
<directory>
    <archive>/archive/c2b/$(stem)/$(name)/$(platform)-$(target)/history</archive>
    <postProcess>/archive/$USER/canopy/$(stem)/$(name)/($platform)-$(target)/pp</postProcess>
    <ptmp>/xtmp/$USER/ptmp</ptmp>
    <analysis>/nbhome/$USER/canopy/analysis/$(name)</analysis>
</directory>
```

We want a similar "FRE-defined" variable expansion capability for the pp.yamls. e.g. how about?

```
  directories:
    history_dir: "/archive/c2b/am5/2022.01/$(expname)/$(platform)-$(target)/history"
    pp_dir: "/archive/$USER/canopy/am5/$(expname)/$(platform)-$(target)/pp"
    ptmp_dir: "/xtmp/$USER/ptmp"
    analysis_dir: "/nbhome/$USER/canopy/analysis/$(expname)"
```

So that users can then use the -e/-p/-t options to `fre pp configure-yaml` to have the same effect, e.g.

`fre pp configure-yaml --yaml=path/to/pp.yaml --experiment=c96L65_am5f1a0r0_amip --platform=gfdl.ncrc5-intel22-classic --target=prod-openmp`
